set_property SRC_FILE_INFO {cfile:{C:/Users/stan/CloudStation/workspaces/workspace Vivado/audio/audio.srcs/constrs_1/new/audio_io.xdc} rfile:../../../audio.srcs/constrs_1/new/audio_io.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports pwm]
