set_property PACKAGE_PIN W5 [get_ports clk100MHz]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]

set_property PACKAGE_PIN T18 [get_ports up]
set_property PACKAGE_PIN U17 [get_ports down]
set_property PACKAGE_PIN W19 [get_ports left]
set_property PACKAGE_PIN T17 [get_ports right]
set_property PACKAGE_PIN U18 [get_ports go]
set_property PACKAGE_PIN V16 [get_ports forward]
set_property PACKAGE_PIN V17 [get_ports backward]

set_property PACKAGE_PIN G19 [get_ports {red[0]}]
set_property PACKAGE_PIN H19 [get_ports {red[1]}]
set_property PACKAGE_PIN J19 [get_ports {red[2]}]
set_property PACKAGE_PIN N19 [get_ports {red[3]}]
set_property PACKAGE_PIN J17 [get_ports {green[0]}]
set_property PACKAGE_PIN H17 [get_ports {green[1]}]
set_property PACKAGE_PIN G17 [get_ports {green[2]}]
set_property PACKAGE_PIN D17 [get_ports {green[3]}]
set_property PACKAGE_PIN N18 [get_ports {blue[0]}]
set_property PACKAGE_PIN L18 [get_ports {blue[1]}]
set_property PACKAGE_PIN K18 [get_ports {blue[2]}]
set_property PACKAGE_PIN J18 [get_ports {blue[3]}]


set_property IOSTANDARD LVCMOS33 [get_ports clk100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports left]
set_property IOSTANDARD LVCMOS33 [get_ports right]
set_property IOSTANDARD LVCMOS33 [get_ports go]
set_property IOSTANDARD LVCMOS33 [get_ports forward]
set_property IOSTANDARD LVCMOS33 [get_ports backward]

set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports pwmsound]
set_property PACKAGE_PIN P18 [get_ports pwmsound]

set_property PACKAGE_PIN W16 [get_ports geluid]
set_property IOSTANDARD LVCMOS33 [get_ports geluid]

set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]

set_property PACKAGE_PIN R2 [get_ports {sw[0]}]
set_property PACKAGE_PIN T1 [get_ports {sw[1]}]
set_property PACKAGE_PIN U1 [get_ports {sw[2]}]
set_property PACKAGE_PIN W2 [get_ports {sw[3]}]
set_property PACKAGE_PIN R3 [get_ports {sw[4]}]
set_property PACKAGE_PIN T2 [get_ports {sw[5]}]
set_property PACKAGE_PIN T3 [get_ports {sw[6]}]
set_property PACKAGE_PIN W13 [get_ports {sw[8]}]
set_property PACKAGE_PIN V2 [get_ports {sw[7]}]

